# docker-compose.yml
# PostgreSQL을 사용하도록 수정되었습니다.

version: '3.8'

services:
  # Spring Boot 백엔드 애플리케이션 서비스
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nexus-backend
    depends_on:
      - db
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - RIOT_API_KEY=${RIOT_API_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_EXPIRATION_MS=${JWT_EXPIRATION_MS}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    restart: always

  # Next.js 프론트엔드 애플리케이션 서비스
  frontend:
    build:
      context: ./frontend
    container_name: nexus-frontend
    ports:
      - "3000:3000"
    restart: always

  # PostgreSQL 데이터베이스 서비스
  db:
    image: postgres:15-alpine # 이미지를 postgres로 변경
    container_name: nexus-db
    environment:
      # PostgreSQL에 맞는 환경변수 이름으로 변경
      POSTGRES_DB: nexusdb
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data # PostgreSQL 데이터 저장 경로
    ports:
      - "5432:5432" # PostgreSQL 기본 포트
    restart: always

volumes:
  db_data:
